version: "3.5"
services:
  svc-geometry:
    image: rust:latest
    container_name: micro-svc-geometry
    volumes:
      - ./services/geometry:/app
      - ./proto:/app/proto:ro
    working_dir: /app
    command: sh ./start.sh
    networks:
      - micro-default
  api-gateway:
    image: node:latest
    container_name: micro-api-gateway
    volumes:
      - ./api-gateway:/app
      - ./proto:/app/proto:ro
    working_dir: /app
    command: sh ./start.sh
    networks:
      - micro-default
networks:
  micro-default:
