version: "3.5"
services:
  svc-geometry:
    image: rust:latest
    container_name: micro-svc-geometry
    volumes:
      - ./services/geometry:/app
      - ./proto:/app/proto:ro
    working_dir: /app
    command: sh ./start.sh
    networks:
      - micro-default
  svc-fibonacci:
    image: maven:latest
    container_name: micro-svc-fibonacci
    volumes:
      - ./services/fibonacci:/app
      - ./proto/fibonacci:/app/src/main/proto:ro
    working_dir: /app
    command: sh ./start.sh
    networks:
      - micro-default
  api-gateway:
    image: node:latest
    container_name: micro-api-gateway
    volumes:
      - ./api-gateway:/app
      - ./proto:/app/proto:ro
    working_dir: /app
    command: sh ./start.sh
    networks:
      - micro-default
    ports:
      - 3000:3000
networks:
  micro-default:
