# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import factorial_pb2 as factorial__pb2


class FactorialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Factorial = channel.unary_unary(
                '/factorial.FactorialService/Factorial',
                request_serializer=factorial__pb2.FactorialReq.SerializeToString,
                response_deserializer=factorial__pb2.FactorialRes.FromString,
                )


class FactorialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Factorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Factorial': grpc.unary_unary_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=factorial__pb2.FactorialReq.FromString,
                    response_serializer=factorial__pb2.FactorialRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factorial.FactorialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FactorialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/factorial.FactorialService/Factorial',
            factorial__pb2.FactorialReq.SerializeToString,
            factorial__pb2.FactorialRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
